# Build image
# `docker-compose -f docker-compose.yml build`
# Push to registry
# `docker-compose -f docker-compose.yml push`

version: '3.8'

services:

  dashboard-ui:
    image: registry.lts.harvard.edu/lts/dashboard-ui:0.0.1
    build:
      context: .
      dockerfile: DockerfilePub