# Build image
# `docker-compose -f docker-compose.yml build`
# Push to registry
# `docker-compose -f docker-compose.yml push`

version: '3.8'

services:

  drs-data-dashboard:
    image: registry.lts.harvard.edu/lts/drs-data-dashboard:0.0.1
    build:
      context: .
      dockerfile: DockerfilePub