# Build image
# `docker-compose -f docker-compose.yml build`
# Push to registry
# `docker-compose -f docker-compose.yml push`

version: '3.8'

services:

  databoard-ui:
    image: registry.lts.harvard.edu/lts/databoard-ui:0.0.4
    build:
      context: .
      dockerfile: DockerfilePub